### ISSUE TITLE
Add support for 'comment' parameter in 'proxysql_mysql_users' module

### ISSUE THREAD

**Issue by BenMayden** [ansible-collections/community.proxysql#166]
##### SUMMARY
The  "community.proxysql.proxysql_mysql_users" module does not support adding comment to the comment column of the mysql_users table.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.proxysql.proxysql_mysql_users

##### ADDITIONAL INFORMATION
The mysql_users table has a "comment" column, however, the "community.proxysql.proxysql_mysql_users" module does not support the comment parameter, and so it cannot add a comment to the comment column for a user.

```
- name: Add a user with a comment
  community.proxysql.proxysql_mysql_users:
    config_file: /some/file/path
    username: user
    password: secretpass
    comment: "Ansible Managed User" <--- This would be a useful parameter
    default_hostgroup: 1
    state: "{{ item.proxysql_state }}"
```
