### ISSUE TITLE
New Module: proxysql_mysql_aws_aurora_hostgroups

### ISSUE THREAD

**Issue by bmildren** [ansible-collections/community.proxysql#5]
##### SUMMARY
Need to add a module to support changes to the mysql_aws_aurora_hostgroups config, along with the associated integration tests.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- proxysql_mysql_aws_aurora_hostgroups

##### ADDITIONAL INFORMATION
`mysql> show create table mysql_aws_aurora_hostgroups\G
*************************** 1. row ***************************
       table: mysql_aws_aurora_hostgroups
Create Table: CREATE TABLE mysql_aws_aurora_hostgroups (
    writer_hostgroup INT CHECK (writer_hostgroup>=0) NOT NULL PRIMARY KEY,
    reader_hostgroup INT NOT NULL CHECK (reader_hostgroup<>writer_hostgroup AND reader_hostgroup>0),
    active INT CHECK (active IN (0,1)) NOT NULL DEFAULT 1,
    aurora_port INT NOT NUlL DEFAULT 3306,
    domain_name VARCHAR NOT NULL CHECK (SUBSTR(domain_name,1,1) = '.'),
    max_lag_ms INT NOT NULL CHECK (max_lag_ms>= 10 AND max_lag_ms <= 600000) DEFAULT 600000,
    check_interval_ms INT NOT NULL CHECK (check_interval_ms >= 100 AND check_interval_ms <= 600000) DEFAULT 1000,
    check_timeout_ms INT NOT NULL CHECK (check_timeout_ms >= 80 AND check_timeout_ms <= 3000) DEFAULT 800,
    writer_is_also_reader INT CHECK (writer_is_also_reader IN (0,1)) NOT NULL DEFAULT 0,
    new_reader_weight INT CHECK (new_reader_weight >= 0 AND new_reader_weight <=10000000) NOT NULL DEFAULT 1,
    comment VARCHAR,
    UNIQUE (reader_hostgroup))`

```yaml
- name: proxysql | config | add aws aurora hostgroups
  proxysql_aws_aurora_hostgroups:
    login_user: 'admin'
    login_password: 'admin'
    writer_hostgroup: 1
    reader_hostgroup: 2
    state: present
    load_to_runtime: False
```
