### ISSUE TITLE
proxysql_mysql_users is not able to handle hashed passwords

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.proxysql#82]
##### SUMMARY
`proxysql_mysql_users` handles passwords only in plaintext.  
Once `MYSQL USERS` is loaded to runtime, proxysql is hashing the passwords automatically. That means:

* `mysql_servers` table holds passwords in plaintext
* `runtime_mysql_servers` table holds passwords hashed.

When you now load `MYSQL USERS` from runtime, and save them to disk, `mysql_servers` holds the user passwords also hashed. But after that, `proxysql_mysql_users` is not able to handle this anymore and is trying to create a new user. This results in errors because of table constraints.

example: ([here is a full playbook example](https://gist.github.com/markuman/fe118b9389eb4376e21251dbf84b398e))

```yaml

    - name: add user to proxysql
      proxysql_mysql_users:
        state: present
        username: someuser
        password: password
        default_hostgroup: 0
        login_user: admin
        login_password: admin
        load_to_runtime: yes

    - name: idempotent add user to proxysql
      proxysql_mysql_users:
        state: present
        username: someuser
        password: password
        default_hostgroup: 0
        login_user: admin
        login_password: admin
        load_to_runtime: yes

    - name: load users back to memory because they are hashed in runtime
      proxysql_manage_config:
        login_user: admin
        login_password: admin
        action: "SAVE"
        config_settings: MYSQL USERS
        direction: "FROM"
        config_layer: "RUNTIME"

    - name: save hashed users also to disk
      proxysql_manage_config:
        login_user: admin
        login_password: admin
        action: "SAVE"
        config_settings: MYSQL USERS
        direction: "TO"
        config_layer: "DISK"

    - name: idempotent add user to proxysql
      proxysql_mysql_users:
        state: present
        username: someuser
        password: password
        default_hostgroup: 0
        login_user: admin
        login_password: admin
        load_to_runtime: yes
```

Result

```
TASK [add user to proxysql] *********************************************************************************************************************************************************************************************************
[WARNING]: Module did not set no_log for encrypt_********
changed: [proxysql]

TASK [idempotent add user to proxysql] **********************************************************************************************************************************************************************************************
ok: [proxysql]

TASK [load users back to runtime because they are hashed in runtime] ****************************************************************************************************************************************************************
changed: [proxysql]

TASK [save hashed users also to disk] ***********************************************************************************************************************************************************************************************
changed: [proxysql]

TASK [idempotent add user to proxysql] **********************************************************************************************************************************************************************************************
fatal: [proxysql]: FAILED! => {"changed": false, "msg": "unable to modify user.. (1045, 'ProxySQL Admin Error: UNIQUE constraint failed: mysql_users.username, mysql_users.frontend')"}
```

References:
* https://proxysql.com/documentation/password-management/
* https://proxysql.com/documentation/configuring-proxysql/

`select password('some-password') as password;` function is not available in proxysql.  
therefore the hash-creation must be implemented within python.

maybe we need a new parameter to control if a password should be hashed or not ...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxysql_mysql_users
